#!/usr/bin/env python
"""
Tabulates parameter counts for every cell
of the locked (activation × PE) Coordinate-MLP grid.

Sanity check before pilots: across a fixed PE column, parameter counts
should differ only by the trainable activation params (~20 for
ScaledSine, 0 for ReLU/Gaussian). Across PEs, parameter counts vary by
the PE's output dimensionality. The latter variation is intrinsic to the
PE design dimension and is accepted.


Writes:
    - markdown table to printout
    - results/param_counts.md (same table, persisted for the paper)
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

from config.architectures import (                                       # noqa: E402
    ACTIVATIONS, PE_CELLS,
    cell_keys, cell_cli_args, display_name,
)

def _params_for_cell(cell_key: str) -> int:
    """Instantiate INR(hparams) for `cell_key` at the locked defaults
    and return its total trainable parameter count."""
    # Local imports — torch / pytorch_lightning are heavy and we want a
    # clean ImportError if they're missing, not a module-load-time crash.
    from config.opts import get_opts
    from models.INR import INR

    cli_args = cell_cli_args(cell_key)

    # Patch sys.argv so get_opts() picks up our flags (it reads sys.argv[1:]
    # for the "explicit overrides" set in addition to parser.parse_args).
    old_argv = sys.argv
    try:
        sys.argv = ['tabulate_params.py'] + cli_args
        hparams = get_opts()
    finally:
        sys.argv = old_argv

    model = INR(hparams)
    return sum(p.numel() for p in model.parameters())



def main() -> None:    
    print(f'Tabulating parameter counts for {len(cell_keys())} cells '
          f'({len(ACTIVATIONS)} activations × {len(PE_CELLS)} PEs)...\n')

    counts: dict[str, int] = {}
    for k in cell_keys():
        try:
            n = _params_for_cell(k)
            counts[k] = n
            print(f'  {k:34s} → {n:>12,} parameters')
        except Exception as e:
            print(f'  ! {k}: failed ({type(e).__name__}: {e})')
            counts[k] = -1

    # ---- Build the markdown report ----
    lines: list[str] = []
    lines.append('# Parameter counts by activation × positional encoding\n')
    lines.append(
        'Generated by `tabulate_params.py`. Values are total '
        'trainable parameter counts for the locked configurations.\n'
    )

    # ---- Main grid: rows = activation, columns = PE ----
    act_keys = list(ACTIVATIONS.keys())
    pe_keys = list(PE_CELLS.keys())
    lines.append('## Coordinate-MLP grid\n')
    header = '| Activation \\ PE | ' + ' | '.join(pe_keys) + ' | INR-Bench (best in row) |'
    sep = '|' + '---|' * (len(pe_keys) + 2)
    lines.append(header)
    lines.append(sep)
    
    for act_key in act_keys:
        row_cells = []
        for pe_key in pe_keys:
            cell_key = f'{act_key}__{pe_key}'
            v = counts.get(cell_key, -1)
            row_cells.append(f'{v:,}' if v >= 0 else 'FAIL')
        lines.append(f'| **{act_key}** | ' + ' | '.join(row_cells) + f' |')

    # ---- Variation summaries -----------------------------------------------
    def _summarize(group_name: str, group_cells: list[str]) -> str:
        vals = [counts[k] for k in group_cells if counts.get(k, -1) > 0]
        if not vals:
            return f'| {group_name} | - | - | - |'
        lo, hi = min(vals), max(vals)
        ratio = hi / lo if lo > 0 else float('inf')
        return f'| {group_name} | {lo:,} | {hi:,} | {ratio:.2f}× |'

    lines.append('\n## Within-activation parameter-count variation\n')
    lines.append(
        "How much does parameter count vary across PEs for a fixed "
        "activation? Driven by the PE's output dimensionality "
        '(intrinsic to the encoding; preregistration §3.2).\n'
    )
    lines.append('| Activation | Min | Max | Max/Min |')
    lines.append('|---|---|---|---|')
    for act_key in act_keys:
        cells = [f'{act_key}__{pe_key}' for pe_key in pe_keys]
        lines.append(_summarize(act_key, cells))

    lines.append('\n## Within-PE parameter-count variation\n')
    lines.append(
        'How much does parameter count vary across activations for a fixed '
        'PE? Should be small (only the trainable activation params differ '
        'between cells in a PE column).\n'
    )
    lines.append('| PE | Min | Max | Max/Min |')
    lines.append('|---|---|---|---|')
    for pe_key in pe_keys:
        cells = [f'{act_key}__{pe_key}' for act_key in act_keys]
        lines.append(_summarize(pe_key, cells))

    table_md = '\n'.join(lines) + '\n'
    print('\n' + table_md)

    # ---- Persist to disk ----
    out_path = REPO_ROOT / 'results' / 'param_counts.md'
    os.makedirs(out_path.parent, exist_ok=True)
    with open(out_path, 'w') as f:
        f.write(table_md)
    print(f'[tabulate_params] wrote {out_path.relative_to(REPO_ROOT)}')


if __name__ == '__main__':
    main()
